### ISSUE TITLE
Building and linking the libgnome shared lib

### ISSUE THREAD

**Issue by ocefpaf** [NOAA-ORR-ERD/PyGnome#15]
The code in

https://github.com/NOAA-ORR-ERD/PyGnome/blob/0ecb501da7e16895fafeee6f62c0202047eaa505/py_gnome/setup.py#L454-L460

sets libpath with `libpath = os.path.join(os.path.abspath(os.path.dirname(__file__)), 'gnome', 'cy_gnome')`

I guess that this will point to the source at `py_gnome/gnome/cy_gnome` and not the `libgnome.so`.

That breaks `python setup.py build`. However, `python setup.py install` does work due to a hard-coded path in https://github.com/NOAA-ORR-ERD/PyGnome/blob/0ecb501da7e16895fafeee6f62c0202047eaa505/py_gnome/setup.py#L443.  That makes it difficult to create a re-relocatable conda package by forcing us to set the a `LD_LIBRARY_PATH` pointing to where `libgnome` is.

**Comment by ocefpaf** [comment]
Taking a close look at this I see a package inside a package (cue inception sequel!)

Here 

https://github.com/NOAA-ORR-ERD/PyGnome/blob/0ecb501da7e16895fafeee6f62c0202047eaa505/py_gnome/setup.py#L427-L436

we get libgnome and later on 

https://github.com/NOAA-ORR-ERD/PyGnome/blob/0ecb501da7e16895fafeee6f62c0202047eaa505/py_gnome/setup.py#L516-L543

We get the rest of py_gnome.

I am uncertain what the devs would like to do here.  I would either split this into separate packages or I would unify the setup() calls.  I see that the first call is only to get the `libgnome.so` path.

**Comment by ChrisBarker-NOAA** [comment]
Yeah, this is pretty kludgy.

I don't think we want to go the separate package route -- in theory, libgnome is a library, but realy it's nonly used with py_gnome and also statically linked to the old GUI-gnome. Really no need to install it as a sytem lib other things can link to.

In the first iteration, all of lib_gnome was compiled in with a single python extension, then all the other extensions could use it, as long as the main one was imported first. But that didn't work on Windows.

So we do a shared lib so that all the extensions can use it. but it's really still intended to be an internal lib.

if we can unity the setup() calls, then that's the way to go.
