### ISSUE TITLE
Building py_gnome w/ Linux, cannot find netcdf.h

### ISSUE THREAD

**Issue by HWR-llc** [NOAA-ORR-ERD/PyGnome#30]
I have successfully built py_gnome on a windows based machine, but I am trying to build it on a Linux machine running Ubuntu 16.04 LTS. When I run `python setup.py install` from `../py_gnome` I get a bunch of warnings, but then get this error:
> ../lib_gnome/TimeGridVel_c.cpp:17:20: fatal error: netcdf.h: No such file or directory
> compilation terminated.
> error: command 'gcc' failed with exit status 1

I looked and netcdf.h is stored in the directory `third_party_lib/..` but the `setup.py` only checks:
`if sys.platform is "darwin" or "win32":`
For me `sys.platform` equals linux2.
So I don't think the correct directory is being assigned for finding netcdf files.

**Comment by ChrisBarker-NOAA** [comment]
We only supply the netCDF lib for Windows and Mac -- for Linux, you need to
install netCDF with the system package manager.

Make sure to install the -dev packages (if the exist) as well as libgnome
needs to build against it.

We are working on updating setup.py to be able to find conda-installed
netCDF, but that isn't working yet.

Pull Requests accepted:-)

-CHB

Sent from my iPhone

On Jul 19, 2017, at 7:21 PM, Matt Hodge <notifications@github.com> wrote:

I have successfully built py_gnome on a windows based machine, but I am
trying to build it on a Linux machine running Ubuntu 16.04 LTS. When I
run python
setup.py install from ../py_gnome I get a bunch of warnings, but then get
this error:

../lib_gnome/TimeGridVel_c.cpp:17:20: fatal error: netcdf.h: No such file
or directory
compilation terminated.
error: command 'gcc' failed with exit status 1

I looked and netcdf.h is stored in the directory third_party_lib/.. but the
setup.py only checks:
if sys.platform is "darwin" or "win32":
For me sys.platform equals linux2.
So I don't think the correct directory is being assigned for finding netcdf
files.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NOAA-ORR-ERD/PyGnome/issues/30>, or mute the thread

**Comment by bhattvihang** [comment]
Hi,

I installed on centos 7 by writing a setup.cfg file. 

vi setup.cfg  (and add following lines)
[build_ext]
include-dirs=/opt/anaconda2/include  (you can select your path)

!wq 

And this solved my issue with installing gnome with anaconda python.

**Comment by ChrisBarker-NOAA** [comment]
thank you!

We do want it to be abel to build with conda-supplied netcdf libs -- so this may be the way to do that.

-CHB

**Comment by farzanehashemabadi** [comment]
I have same problem with build py_gnome on centOS, can you help me?

**Comment by ChrisBarker-NOAA** [comment]
which branch are you building? This has been updated recently.

And please post what error messages you get.

-CHB

**Comment by farzanehashemabadi** [comment]
> which branch are you building? This has been updated recently.
> 
> And please post what error messages you get.
> 
> -CHB

I build PyGnome-Master branch. my Erros show below.
![Error](https://user-images.githubusercontent.com/71126340/106390164-4e35f700-63fc-11eb-915d-b6db4ed26837.JPG)
