### ISSUE TITLE
Expected output types from PyGnome

### ISSUE THREAD

**Issue by jwsvargas** [NOAA-ORR-ERD/PyGnome#38]
Hello NOAA folks!

In the desktop version I used to save the simulations in _NOAA Standard Splot File Series_ format in order to run some post-processing like drawing slick boundaries, estimating area etc. I noticed the new _geojson_ format, which was completely new for me. My question is, are you going to stick to _geojson_ format or we should expect other options, including the ones which are available at the desktop version? What is the idea behind the change for this new format?

Look forward to hearing from you.

Cheers!

**Comment by ChrisBarker-NOAA** [comment]
It's actually pretty easy to add other output options, so we may add more.

However, we probably won't support the "NOAA Standard Splot File Series" format, as while it is, I suppose, a NOAA standard, it's not a format that anyone else uses or can work with. So we are moving to more standard formats.

GeoJSON is one, as is KML, and Shapefiles.

For the most full-featured output, netcdf is your best best. It conforms to this semi-standard:

https://github.com/NOAA-ORR-ERD/nc_particles/blob/master/nc_particle_standard.md

What tools were you using for post-processing?

**Comment by jwsvargas** [comment]
Hi, Chris!

I'm using MATLAB for post-proc. There are a couple of scripts I've made to estimate the area, to calculate variance and mean position, to draw the boundary and stuff like that. The purpose of it all was to write down a report. I guess I'll have to change the scripts to work on the PyGnome output now. :D 

I'm a complete noob on NetCDF, but I think to code for reading particle positions for NetCDF should be way less straightforward than for the splot file series, am I right?

**Comment by ChrisBarker-NOAA** [comment]
well, MATLAB supports netcdf pretty well, so that part shouldn't be hard.

The tricky bit is that the nc_particles format supports a different number of particles for each timestep, as often models create and destroy particles as they run.

In the older version, GNOME would great all the particles up front, and then mark them as "not reelased" or "off map". But that was getting unsustainable with really long runs....

So it now doesn't add the particles until they are needed, and it removes them when they go off the map (if they do).

Anyway, netcdf doesn't support "ragged arrays" directly, so there is a bit of logic needed to unpack the data.

See the Python code here:

https://github.com/NOAA-ORR-ERD/nc_particles/tree/master/python_implementation

it should be pretty easy to translate to MATLAB.

And we'd love it you wanted to contribute a MATLAB version to that project -- the more people that can read the format, the better.

Alternatively, use the geoJSON or shapefiles....

**Comment by jwsvargas** [comment]
Ok, Chris. Thank you for the info. I'll see what I can do. 

One more thing, is there some sort of webinar, video lecture or something like that that covers the basics of PyGnome? I found a lecture of yours from ScyPy in Youtube, but I think I'm gonna need something more thorough. I ask you that because I am by myself here, trying to learn it from scratch. Because of that I may be asking you a little too much. :D 

Thanks again.

**Comment by ChrisBarker-NOAA** [comment]
I'm afraid not.

And the docs are pretty sparse, I know. But ask questions, and we'll try to answer them, and maybe add to the docs when we do.

-CHB

**Comment by jwsvargas** [comment]
That's ok. 

Thank you very much.

**Comment by ChrisBarker-NOAA** [comment]
Oh, jsut to make sure, you did find this:

http://noaa-orr-erd.github.io/PyGnome/scripting.html

I hope!
