### ISSUE TITLE
Problem in ShapeOutput/specific result required

### ISSUE THREAD

**Issue by fSohrabi75** [NOAA-ORR-ERD/PyGnome#82]

**Comment by ChrisBarker-NOAA** [comment]
Sorry I missed this earlier.

IIUC, The Shapefile OUtputter isn't really designed to do that. It puts all the timesteps in one (set of) shapefiles.

Each timestep gets an attribute with teh timestamp, so that post-processing tools can keep them apart.

However, you may be able to "fake" it with something like (untested):

```
import gnome.scripting as gs

for i in range(1, 30, 1):
        
     model.outputters += gs.ShapeOutput(os.path.join(base_dir, 'gnome_result {id}'.format(id=i)),
                                                                                       zip_output=False,
                                                                                       output_start_time=start_time + gs.days(i)
                                                                                       output_timestep=gs.days(100)  # or something big
                                                                                       output_zero_step=False,
                                                                                       output_last_step=False,
                                                                                      )
```
That will create a new outputter for each day (with the filename you set) Each one will only start outputting after i days. and I'm hoping the large output timestep will mean it never outputs a second step.

Setting output_zero_step and  output_last_step to False means it won't output at the beginning and end of the model run either.
