### ISSUE TITLE
Python 3.8?

### ISSUE THREAD

**Issue by moisespr123** [NOAA-ORR-ERD/PyGnome#99]
Hello,

I'm asking if there are some compatibility issues if we use Python 3.6. We've been developing using this version under Conda and it seems to be running fine. However, your documentation states Python 3.8 and up is needed.

Are there compatibility issues when using Python 3.6 that I may not be aware of, or do you plan on developing this module to just support Python 3.8 and up in the future?

Thanks
-Moises

**Comment by ChrisBarker-NOAA** [comment]
We're using 3.8 in development. I don't know of any issues with 3.6, but one might creep in, since we're not testing with older versions.

There were some issues with 3.9 with py2 compatibility, which is why we aren't using that. but we're dropping the py2 compatibility so that may change.

Also: we are about to transition to a new OIl Data codebase: 

https://github.com/NOAA-ORR-ERD/adios_oil_database

And that will not work with py3.6, though could probably be backported (it uses dataclasses, which are not in py3.6, but there is a package on PyPi that's compatible)

Any reason you have to stick with 3.6? it's getting pretty old now and 3.8 is, as far as I know, fully backward compatible.

**Comment by moisespr123** [comment]
Thanks. I was just curious. In the meantime, it is working fine under Conda. Without conda I'm getting a `py_gd` issue but that may be due to a dependency on our docker instance. I'm still trying to figure it out (See #100).

The reason for using Python 3.6 is because it's a client requirement.

**Comment by ChrisBarker-NOAA** [comment]
NOTE: if you continue to need Py3.6 support, if you want to contribute a test setup on the gitHub CI, at least we'll find out sooner than later if we've broken it, and can fix or backport as needed.

We're doing 

CI on our internal system, but only with 3.8
